name: 每 6 小时自动更新 random_ips.txt（生成并保存到仓库）

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时执行一次（UTC 时间）
  workflow_dispatch:
    inputs:
      prefix:
        description: 'IP 前缀'
        required: false
        default: '172.64.229'

jobs:
  generate_ips:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码（允许提交修改）
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # 保证 GitHub Token 可用于提交

      - name: 清空旧 IP 并生成新 IP
        run: |
          PREFIX="${{ github.event.inputs.prefix }}"
          FILE="random_ips.txt"

          # 如果文件存在且非空，清空内容
          if [ -s "$FILE" ]; then
            echo "检测到旧 IP，已清空文件"
            > "$FILE"
          else
            echo "文件不存在或为空，创建并写入新 IP"
            touch "$FILE"
          fi

          # 生成 10 个随机 IP
          for i in $(seq 1 10); do
            LAST=$(( (RANDOM % 200) + 1 ))
            echo "${PREFIX}.${LAST}" >> "$FILE"
          done

          echo "完成写入新 IP"

      - name: 显示生成的 IP 内容
        run: cat random_ips.txt

      - name: 提交并推送到仓库
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet; then
            git add random_ips.txt
            git commit -m "🤖 自动更新 IP: $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "文件未变化，跳过提交。"