name: 每 6 小时生成 10 个随机 IP 到 TXT（无需提交，无需创建）

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时运行一次（UTC时间）
  workflow_dispatch:
    inputs:
      prefix:
        description: 'IP 前缀'
        required: false
        default: '172.64.229'

jobs:
  generate_ips:
    runs-on: ubuntu-latest

    steps:
      - name: 检查并清空旧 IP，写入新 IP
        run: |
          PREFIX="${{ github.event.inputs.prefix }}"
          FILE="random_ips.txt"

          # 如果文件存在且非空，清空旧内容
          if [ -s "$FILE" ]; then
            echo "检测到旧 IP，已清空文件。"
            > "$FILE"
          else
            echo "文件不存在或为空，将写入新 IP。"
          fi

          # 生成 10 个随机 IP，尾段在 1~200 范围内
          for i in $(seq 1 10); do
            LAST=$(( (RANDOM % 200) + 1 ))
            echo "${PREFIX}.${LAST}" >> "$FILE"
          done

      - name: 显示生成的 IP
        run: cat random_ips.txt