name: Generate Random IPs

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  generate-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Run IP generator
      run: python generate_ips.py
      
    - name: Upload generated IPs
      uses: actions/upload-artifact@v3
      with:
        name: generated-ips
        path: generated_ips.txt
