name: Auto Update Random IPs

on:
  schedule:
    # 每 6 小时运行一次
    - cron: "0 */3 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  generate-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate random IPs
      run: |
        python -c "
        import random;
        random_ips = ['172.64.229.' + str(random.randint(1,255)) for _ in range(6)];
        with open('random_ips.txt', 'w') as f:
            f.write('\\n'.join(random_ips))
        "

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add random_ips.txt
        git commit -m 'Update random IPs'
        git push