name: Auto Update Random IPs

on:
  schedule:
    - cron: "0 16,22,4,10 * * *"
  workflow_dispatch:

jobs:
  generate-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate random IPs
      run: |
        python -c "
        import random;
        # 控制每个前缀生成的IP数量
        ip_count_per_prefix = 1
        
        # 生成172.64.229.xx段的随机IP
        prefix1_ips = ['172.64.229.' + str(random.randint(1,255)) for _ in range(ip_count_per_prefix)]
        
        # 生成43.174.150.xx段的随机IP
        prefix2_ips = ['43.174.150.' + str(random.randint(1,255)) for _ in range(ip_count_per_prefix)]
        
        # 合并所有IP
        all_ips = prefix1_ips + prefix2_ips
        
        with open('random_ips.txt', 'w') as f:
            f.write('\\n'.join(all_ips))
        "

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add random_ips.txt
        git commit -m 'Update random IPs'
        git push